# Generated by Django 6.0.6 on 2026-07-06 07:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=100)),
                ('hatch_date', models.DateField()),
                ('quantity_total', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_reserved', models.PositiveIntegerField(default=0)),
                ('quantity_collected', models.PositiveIntegerField(default=0)),
                ('price_per_chick', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold_out', 'Sold Out'), ('closed', 'Closed')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='warehouses.collectionpoint')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
